joshmedeski/t-smart-tmux-session-manager

bin/t

I tried running this script on linux. It failed. I'm assuming it's because `t` isn't POSIX compliant, but I don't know enough about shell scripting to say this confidently.
I don't use macOS regularly, so I may be wrong. On macOS, `/bin/sh` is `bash`. But on linux `/bin/sh` is usually `dash`. `t` fails to run on `dash`. This can be observed by changing the shebang to call `dash` instead of `sh`. But since `t` was written to be called on `bash`, a simple fix is to just change the shebang so it works on linux.
I've tested these changes on an M1 mac. It should work on any machine that has `bash` installed. 
An even better fix is to fix this script so that it can run on `dash`. I can begin working on this.

Add linux support for `t`

---

bin/t

Currently, there's an issue with sessions that share substrings in their names. For example; say you have the sessions `test` and `testing` in `foo/test` and `bar/testing` respectively, trying to jump to `test` would result in `tmux list-sessions | grep -F "$SESSION_NAME"` finding both sessions, which may fail or have undefined behavior.
This PR aims to fix this by using tmux's `-F` flag to only list sessions by their name and making sure grep finds the exact session name using regex `^`(start of string) and `$`(regex end of string).

fix: Allow session whos names are substings of other sessions

---

bin/t

New feature! Current tmux sessions are now listed at the top of the fzf list. I've found that I often want a session that's already open so it's now first in the fzf list for quick access and matching.
I've also added keyboard shortcuts to allow you to toggle between tmux sessions ctrl-s, zoxide entries ctrl-x (ctrl-z is a reserved keybinding), and all results ctrl-a for more fine-grained control.

feat: list tmux sessions and zoxide

---

bin/t

- refactor: create a conditional guard for help
- fix: improve how the tmux session is detected (by reading exit code)
- refactor: improve code comments
- refactor: break fzf commands into multiple lines
- fix: remove bindings to fzf script when tmux isn't running
- fix: drop $HOME substitution (was causing bugs)
- fix: only lookup the tmux session if tmux is running
- feat: change from cd to result to using tmux -c flag to set session directory

refactor: improve the script

---

bin/t

Closes #9 
If you pass an argument to the `t` script and there is no matching zoxide result, it will use the argument as a directory and attempt to create a tmux session. It throws an error if that directory doesn't exist.

feat: use argument as path if no zoxide result

---

README.md
bin/t

Closes #8 
Switching `ctrl-p` to `ctrl-d` (directory) since `ctrl-p` is a reasonable default for going to the previous result in fzf.

feat: switch ctrl-p to ctrl-d

---

bin/t

Sorry, was a bit quick with my last PR and didn't test it enough 😓
Fixes #10
This time it reverses the alias back to `$HOME` before being used.
I also realized that `sed` treats some chars as special chars so now it only aliases if safe to use `$HOME` unescaped in `sed`.
The current allowed chars are pretty strict and could probably be expanded.

feat: alias $HOME as '~' if safe to do so

---

README.md
bin/t
t-smart-tmux-session-manager.tmux

- Add ability to customize the fzf prompt
- Drop the fzf `--reverse`
- Drop the "all" keybinding as it wasn't working properly
- Add docs for how to customize the prompt
- Add docs for recommended tmux settings
- Minor formatting updates
- Break fzf commands into separate lines and sort flags alphabetically
Here's a preview of the custom prompt:

Custom Prompt, FZF Updates, Tmux Recommendations

---

README.md
t-smart-tmux-session-manager.tmux

This also addreses the issue that section about the custom keybind would have required the script to be already added to PATH

feat: custom user keybind, unbind default keybind

---

bin/t

This is something that I missed from my own script.
It allows you to use the picker like an "alt+tab" of sorts.

feat: sort existing sessions by mru

---

bin/t
cspell.json

Closes #41 
Binds `tab` to go down to the next fzf selection and `shift+tab` to go up to the previous fzf selection.
Thanks @RiteshChepuri, after implementing it I can see the benefit!

feat: add tab key binding to cycle fzf

---

README.md
bin/t

Closes #44 
Ability to use the user specifed `FZF_TMUX_OPTS` to overwrite the `fzf-tmux` behavior.

feat: allow FZF_TMUX_OPTS overwrite

---

README.md
bin/t

Closes #50 
Adds the ability to set `T_SESSION_NAME_INCLUDE_PARENT` to your shell and enable session names to include their parent directory.
You can test this by updating your tpm entry to:
```
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager#parent-dir-session-name'
```
The reinstall the tpm package.
Next, you'll need to add the `T_SESSION_NAME_INCLUDE_PARENT` variable to your shell.
<details>
<summary>bash</summary>
Add the following line to `~/.bashrc`
```sh
export T_SESSION_NAME_INCLUDE_PARENT="true"
```
</details>
<details>
<summary>zsh</summary>
Add the following line to `~/.zshrc`
```sh
export T_SESSION_NAME_INCLUDE_PARENT="true"
```
</details>
<details>
<summary>fish</summary>
Add the following line to `~/.config/fish/conf.d/t.fish`
```fish
set -Ux …
```

Parent dir session name

---

bin/t

Add the ^x zoxide bind even in serverless mode because once you use find bind you can no longer go back to zoxide listing.
resolves #57

feat(binary): add zoxide bind to serverless mode

---

README.md
bin/t

Closes #53 
Generates sessions names by getting the root of the monorepo and building a session name starting from the root.

feat: add git root session name support

---

README.md
bin/t

Closes #66 
By default, t will display tmux sessions and zoxide results by default. You can change this by setting `@t-fzf-default-results` variable to your `tmux.conf`:
```sh
set -g @t-fzf-default-results 'sessions' # show tmux sessions by default
```
```sh
set -g @t-fzf-default-results 'zoxide' # show zoxide results by default
```

Customizing default fzf results

---

.t
README.md
bin/t

You can run a startup script when you create a new session. This is useful for running a command when you create a new session, like starting a dev server or automatically opening neovim to begin editing a file.
This works by adding a `.t` file to your desired directory. Here is a quick script for bootstrapping that file:
```sh
touch .t && chmod +x .t && echo -e '#!/usr/bin/env bash\n' > .t && nvim .t
```
I like opening Neovim and the find file Telescope prompt to quickly find a file to edit. Here is an example of what I put in many of my projects:
```sh
#!/usr/bin/env bash
nvim -c 'Telescope find_files'
```
So, when you open any project that detects a `.t` it will automatically run that script when a session is created.
This feature is in early development so please feel free to give …

Startup script (.t)

---

README.md
bin/t

I've gotten half a dozen or more issues related to people not upgrading to bash >= 4. I was able to convert the bash script to  be compatible with version 3, which is what most macs ship with. Hopefully this reduces issues!

Downgrade bash

---

bin/t

Sometimes there are (unfortunately) git submodules in the projects I clone down. Would be nice if `t --repos` would just clone down all of those by default.
Low-effort contribution where I just added `--recursive` to be the default to the `git clone` command. 😄
I was first thinking of forwarding any arguments onto `git clone`, so I could just run `t --repos --recursive <url>` myself. But then I see you are already mucking around quite a lot with arguments so I didn't want to go down that route, just to keep this simple.
But in case you want to explore the ability to forward args to `git clone`, it might be possible to shift past the `-r`/`--repos` args:
```bash
#!/bin/bash
directory_cmd() {
echo "Running directory command with arguments: $@"
}
repos_cmd() {
echo "Running repos command …
```

feat: add --recursive to "git clone"

---

bin/t

I find myself usually use t keybinding and then enter to switch to alternative session (same result could be achieved with prefix + L).
Default behavior list current session in the session list make no sense because I don't want to jump to current session. 
I notice `tmux list-sessions` command also have `--filter` argument so I try to filter out current session with session unique ID.
Please let me know if I could write better script cause I'm not good with scripting.
Thanks for amazing tmux plugins.

fix: exclude current session from session list

---

bin/t

- **Issue**: The tmux session_name will be displayed as the name `main` if I'm using `git worktree` to manage my git project. 
- **Solution**: Add the project name to the session_name. 
- **before**:
- `main`
-  `add-xxx-support`
- **after**:
- `infra/main`
-  `infra/add-xxx-support`
---

feat: add `git worktree` support

---

bin/t

Hi Josh,
still enjoying the t session manager a lot (looking forward to the rewrite in Go), but here's something that has been bugging me for a while.
Sometimes I get confused by the fact that my **active tmux sessions are listed together with the rest of the options** (zoxide etc.) to choose from. I've added a small horizontal separator line and for me this is a really helpful detail.
Perhaps you'd like to merge this? Not sure if it's 100% the correct way to do this, also wondering whether all terminals will render the hardcoded UTF-8 em dash correctly, but it's so much prettier than the ASCII single dash `- `!
All the best,
Tom.

Add separator line

---

bin/t

I like to copy URL directly from the omnibox of browser reference: #100
Very small PR, but this really hinders my workflow. If merged I wouldn't have to manage my own fork :)

feat: make `.git` in repo url optional
